### ISSUE TITLE
Finer-grained inclusion/exclusion when gathering webmentions

### ISSUE THREAD

**Issue by Seirdy** [nekr0z/static-webmentions#1]
## Problem

Loving `static-webmentions` so far, but better exclusion mechanisms would be helpful:

- I add Webmentions to my website at build-time, and label their links with `rel=nofollow`. If I send webmentions to these webmentions, we could end up with a feedback loop.
- My `<footer>` has links that are included in every page. Currently, I manually add the links in my footers to the exclude list in `config.toml`, but I might eventually add links that change (like a link to the latest git commit displayed by my preferred git forge).

## Proposed solutions

Two possible solutions that are not mutually exclusive:

### Solution 1: exclusions

- Exclude links with `rel="nofollow"` or `rel="ucg"`.
- Exclude children of certain tags (e.g., `<footer>` or `<section class="webmentions">`

### Solution 2: finer-grained inclusions

Currently, static-webmentions extracts the content of `.h-entry`. If it only extracts `.e-content` when it's present, then it will only gather pending webmentions from links in the article text.

If you have a preferred solution, I could implement it this weekend.

**Comment by Seirdy** [comment]
An alternative solution could be to use a library like [go-readability](https://github.com/go-shiori/go-readability) to extract the article HTML, and then extract webmentions from that.

**Comment by nekr0z** [comment]
>  static-webmentions extracts the content of `.h-entry`

This is intended. It's common practice to include, for example, `u-in-reply-to` links into `.h-entry`, but outside of `.e-content`, which is totally logical.

>  Exclude children of certain tags (e.g., `<footer>` or `<section class="webmentions">`

I like this solution better. Obviously, it has to be configurable, so that a user can define in the config which tags and childred thereof are to be excluded.

However, before you rush to implement, consider this:

> The purpose of an entry is to place it around both the explicitly written content (in the content property or in other specific properties for non-textual content or responses) and whatever else is the context for that content, including properties for when it was published and/or updated, who created it, tags or categorization, and links to what the content is a response to (perhaps with a quoted excerpt) and/or links to syndicated copies. 
>
> – [microformats wiki](http://microformats.org/wiki/h-entry)

One can argue that the list of webmentions belongs inside `h-entry`. I (personally) don't think it does, and the lack of a suitable _property_ seems to be in favour of my opinion.

Looking at your particular site (and thank you for it, I'm a subscriber) I think your `h-entry` is too inclusive. I personally would only mark `<article>` as `h-entry` (I actually do just that on my own website), since I think it's more in line with the intended use of `h-entry` microformat, as quoted above. Again, the webmentions part — maybe, but the `<footer>` obviously doesn't belong there. But `<footer>` isn't an issue here at all, since it always has the same links, so this case is covered by the existing `excludeDestinations` option.

**Comment by Seirdy** [comment]
Sounds good; I learned something today.

I [just moved](https://git.sr.ht/~seirdy/seirdy.one/commit/a370429a2e3443fdb7d33dd8a0045277d6292042) the end of my `h-entry` up a bit so it includes the syndicated copy to my Gemini capsule (for all 0 services supporting both microformats and Gemini :P).

Regarding wildcard support: I'm currently [using jq](https://git.sr.ht/~seirdy/seirdy.one/tree/c2404ce5525453286a8dc24ec0ba62f269ddac77/item/Makefile#L83) to do more elaborate regex-based exclusions after generating the JSON. Including a full PCRE implementaiton would be a bit much; I think that delegating advanced URL filtering (after parsing is already done) to external programs would be preferable. But that's a relatively weakly-held opinion and I'm find with whatever you prefer.

**Comment by nekr0z** [comment]
> But that's a relatively weakly-held opinion and I'm find with whatever you prefer.

I found (the hard way) that it's very hard to do IndieWeb without firmly standing on the [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) ground, so I try to keep `static-webmentions` development on scratch-the-itch basis as much as possible. As long as your setup fits your needs and all the itches are being scratched by it to your satisfaction, there's no need to add code and bugs. ;-)

Naturally, where code is needed, code needs to be written, and the tag-based exclusion might be just such a case (if you do feel that incoming webmentions actually belong inside the `h-entry`).

**Comment by Seirdy** [comment]
> if you do feel that incoming webmentions actually belong inside the `h-entry`

Fortunately, I don't. Feel free to close :)

**Comment by nekr0z** [comment]
Right.

Feel free to reopen — anybody! — if the need arises.

**Comment by nekr0z** [comment]
OK, after re-reading the spec again I'm reopening this, with a little bit of twist.

The spec [states](https://www.w3.org/TR/webmention/#sending-webmentions-for-updated-posts):
>  If a response to the source URL is shown on the source URL page (e.g. as a comment), then sender SHOULD treat that as an update of the source URL and re-send any previously sent Webmentions.
This means that in both my and @Seirdy's cases (and for anyone who is showing the received webmentions by statically compiling them into the page, as opposed to dynamically showing them client-side using JS):
1. the webmentions need to be re-send when a new comment appears on the page (not necessarily inside the `h-entry`, though that would be preferrable if we are to support [salmentions](https://indieweb.org/Salmention)), hence we need
    - [ ] an option to specify a class (or several) that would be included in changes discovery along with the existing `h-entry`;

2. not sending webmentions to the replies to avoid webmention loops is sane, so we also need
    - [ ] an option to specify a class (or several) that would be excluded from gathering targets when sending webmentions.

**Comment by nekr0z** [comment]
Done, already in pre-release. Will be in 0.5.0.

Closing for good now :)
